steps:
  - input: "Build parameters"
    if: build.source == "ui"
    fields:
      - select: "Rebuild?"
        key: "REBUILD"
        default: false
        required: false
        options:
          - label: "no"
            value: false
          - label: "yes"
            value: true
        hint: "Should all books be rebuilt, regardless of what has changed? Build once with this set to true after every release."
      - select: "Allow Broken Links?"
        key: "ALLOW_BROKEN_LINKS"
        default: false
        required: false
        options:
          - label: "no"
            value: false
          - label: "yes"
            value: true
        hint: "Should we ignore broken links? Ignoring broken links is dangerous not just because bad links will leak into the public site but because subsequent builds and pull requests that do not fix the links fail."
  - wait
  - label: ":white_check_mark: Build docs"
    command: |
      export REBUILD="$(buildkite-agent meta-data get REBUILD --default false)"
      export ALLOW_BROKEN_LINKS="$(buildkite-agent meta-data get ALLOW_BROKEN_LINKS --default false)"
      bash .buildkite/scripts/build-docs.sh
    #branches: "master"
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204


