steps:
  - label: ":white_check_mark: Build docs"
    command: .buildkite/scripts/build-docs.sh
    # TODO - add condition to run only on master, for PR or merges
    env:
      REBUILD: false
      SKIP_LINK_CHECK: false
      ALLOW_BROKEN_LINKS: false
    agents:
      provider: "gcp"
      image: family/docs-ubuntu-2204
